#!/bin/bash

if [ ! -d "${GITROOT}" ]; then
  elog "No git repository found"
  exit 1
fi

rm -rf "${EXECDIR}" "${ENVDIR}" "${EXPODIR}"
mkdir -p "${ENVDIR}" "${EXECDIR}" "${ENTRYDIR}" "${EXPODIR}" "${ENDODIR}" "${CACHEDIR}"

rm -f "${CONFIG}"
touch "${CONFIG}" "${MNEMONIC}"

cat <<EOF >"${CONFIG}"
[entry factor_global]
url=""
tag=master
env=""
endo=""
exec=""
EOF

cat <<EOF >"${ENVDIR}/factor_default"
GITROOT="${GITROOT}"
IFIO_PATH="${EXECDIR}"
EOF

cat <<EOF >"${ENVDIR}/factor_isolation"
PATH="${PATH}:${GITROOT}/.factor/bin"
EOF

find "${GITROOT}" -type f -name "*.ftr" | \
while read file; do
  cat "${file}" >> "${CONFIG}"
done

# Output execs
egrep '\[\s*exec .*\]' "${CONFIG}" | \
  sed 's/\[\s*exec //;s/\]\s*$//' | \
  while read sect; do
    wzk-sekt -t 'exec' "${CONFIG}" "${sect}" > "${EXECDIR}/${sect}"
    chmod +x "${EXECDIR}/${sect}"
  done

# Output envs
egrep '\[\s*env .*\]' "${CONFIG}" | \
  sed 's/\[\s*env //;s/\]\s*$//' | \
  while read sect; do
    wzk-sekt -t 'env' "${CONFIG}" "${sect}" > "${ENVDIR}/${sect}"
  done

# Generate entry dirs
egrep '\[\s*entry .*\]' "${CONFIG}" | \
  sed 's/\[\s*entry //;s/\]\s*$//' | \
  while read sect; do
    mkdir -p "${ENTRYDIR}/${sect}"
    touch "${ENTRYDIR}/${sect}/state"
  done

# Output expos
egrep '\[\s*expo .*\]' "${CONFIG}" | \
  sed 's/\[\s*expo //;s/\]\s*$//' | \
  while read sect; do
    wzk-sekt -t 'expo' "${CONFIG}" "${sect}" > "${EXPODIR}/${sect}"
  done

# Generate endo dirs
egrep '\[\s*endo .*\]' "${CONFIG}" | \
  sed 's/\[\s*endo //;s/\]\s*$//' | \
  while read sect; do
    mkdir -p "${ENDODIR}/${sect}"
  done

# Copy in the BBROOT
if [ ! -d "${FDIR}/bin" ]; then
  mkdir -p "${FDIR}/bin"
  bbtar="$(realpath $(dirname $(which wzk-factor))/../share/wzk/bbroot.tar.gz)"
  cd "${FDIR}/bin"
  tar zxf "${bbtar}" -C./
fi
