#!/bin/bash

_sync_to_build() {
  mkdir -p "${f_prefix}"
  rsync -av "${f_cache}/" "${f_prefix}/"
}

if [ ! -z "${f_url}" ]; then
  _sync_to_build | @v "$(@s "${1}" 5 "Syncing")"
fi

@s "${1}" 6 "Updating locks" clear
cat <<EOF >"${f_meta}"
[metadata ${1}]
hash=${curr_hash}
tag=${f_tag}
EOF

@s "${1}" 7 "Done" clear
echo
